menu:
  博文: /
  归档: /archives/
  生活: /categories/live/
  读书: /categories/read/
  关于: /about/

widgets:
  - category
  - tag
  - tagcloud
  - archive

# count
show_count: true
favicon: https://leeway2zcblog-1373523181.cos.ap-guangzhou.myqcloud.com/img/favicon.ico
logo: https://leeway2zcblog-1373523181.cos.ap-guangzhou.myqcloud.com/img/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250811154253_3.jpg
style: https://bubuzou.oss-cn-shenzhen.aliyuncs.com/blog/202010/bubuzou.css

# Comment
#changyan: bubuzou
leancloud:
  appid: aD8jJBpu4oew3ovNY73z6Rdq-gzGzoHsz # 填写您的appid
  appkey: FdzS5SOPHdhYQoEUngQ8K2QW # 填写您的appkey
  comment: true # 是否开启评论系统
  timer: false # 是否开启文章统计

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
